# Generated by Django 4.2.7 on 2023-11-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=100, verbose_name='รายการครุภัณฑ์')),
                ('unit', models.CharField(max_length=2, verbose_name='หน่วย')),
                ('type_1', models.CharField(max_length=5, verbose_name='ประเภท')),
                ('type_2', models.CharField(max_length=5, verbose_name='ชนิด')),
                ('type_3', models.CharField(max_length=5, verbose_name='ลักษณะ')),
                ('degree', models.CharField(max_length=10, verbose_name='ลำดับ/ปี')),
            ],
            options={
                'verbose_name_plural': 'รายการครุภัณฑ์และเลขครุภัณฑ์',
                'ordering': ('id',),
            },
        ),
    ]
