# Generated by Django 4.2.7 on 2023-11-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='ยี่ห้อ/รุ่น')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='หมายเหตุ')),
                ('date_check', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ตรวจสอบ')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='ปีงบประมาณ')),
                ('imgge_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='รูป 1')),
                ('imgge_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='รูป 2')),
                ('imgge_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='รูป 3')),
                ('CheckList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.checklist', verbose_name='สถานะที่ตรวจพบ')),
                ('Itemname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.itemname', verbose_name='ครุภัณฑ์')),
                ('Locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.locations', verbose_name='สถานที่ใช้งานในปัจจุบัน')),
                ('NumberList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.numberlist', verbose_name='เลขครุภัณฑ์')),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_items', to='dropdown.person', verbose_name='ผู้รับผิดชอบ')),
                ('user_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_check_items', to='dropdown.person', verbose_name='ผู้ตรวจเช็ค')),
            ],
            options={
                'verbose_name_plural': 'ตรวจสอบครุภัณฑ์',
                'ordering': ('-id',),
            },
        ),
    ]
