# Generated by Django 4.2.7 on 2023-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='status',
            field=models.CharField(choices=[('ชำรุด', 'ชำรุด'), ('เสื่อม', 'เสื่อม'), ('สูญไป', 'สูญไป'), ('ไม่ใช้', 'ไม่ใช้'), ('ใช้อยู่', 'ใช้อยู่')], default='ใช้อยู่', max_length=10, verbose_name='สถานะ'),
        ),
    ]
