# Generated by Django 4.2.7 on 2023-11-15 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_listnumber'),
        ('checkitem', '0003_remove_checkitem_status_alter_checkitem_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkitem',
            old_name='CheckList',
            new_name='checkList',
        ),
        migrations.RenameField(
            model_name='checkitem',
            old_name='Locations',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='checkitem',
            old_name='Person',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='checkitem',
            name='Itemname',
        ),
        migrations.RemoveField(
            model_name='checkitem',
            name='NumberList',
        ),
        migrations.AddField(
            model_name='checkitem',
            name='listnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.listnumber', verbose_name='รายการครุภัณฑ์และเลขครุภัณฑ์'),
        ),
    ]
