# Generated by Django 4.2.7 on 2023-11-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkitem', '0004_rename_checklist_checkitem_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkitem',
            name='year',
        ),
        migrations.AddField(
            model_name='checkitem',
            name='note_list',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='หมายเหตุ(รายการครุภัณฑ์)'),
        ),
    ]
