# Generated by Django 4.2.7 on 2023-11-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkitem', '0005_remove_checkitem_year_checkitem_note_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='imgge_1',
            field=models.ImageField(blank=True, null=True, upload_to='upload_list', verbose_name='รูป 1'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='imgge_2',
            field=models.ImageField(blank=True, null=True, upload_to='upload_list', verbose_name='รูป 2'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='imgge_3',
            field=models.ImageField(blank=True, null=True, upload_to='upload_list', verbose_name='รูป 3'),
        ),
    ]
