# Generated by Django 4.2.7 on 2023-11-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkitem', '0007_rename_imgge_1_checkitem_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='รูป 1'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='รูป 2'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='รูป 3'),
        ),
    ]
