# Generated by Django 4.2.7 on 2023-11-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkitem', '0008_alter_checkitem_image_1_alter_checkitem_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='year',
            field=models.CharField(blank=True, default='2566', max_length=4, null=True, verbose_name='ปีที่ตรวจ'),
        ),
    ]
